GET http://127.0.0.1:3000/api/index


### All Books

GET http://127.0.0.1:3000/api/books

### Search

GET http://127.0.0.1:3000/api/books?title=Python&publishedAfter=&publishedBefore=

### Single book by id

GET http://127.0.0.1:3000/api/books/5ef2fcf5aca4661c381b7510

### Delete by id

DELETE http://127.0.0.1:3000/api/books/5ef2fcf5aca4661c381b7510


### Author

GET http://127.0.0.1:3000/api/authors


### Single Author

GET http://127.0.0.1:3000/api/authors/5ef31aedb655940cf8735f6a


###

DELETE http://127.0.0.1:3000/api/authors/5ef31aedb655940cf8735f6a

### 
POST http://127.0.0.1:3000/api/authors
Content-Type: application/json

{
    "name": "Pamela Wakoli"
}

### 
PUT http://127.0.0.1:3000/api/authors
Content-Type: application/json

{
    "name": "Pamela Wakoli"
}